#!/bin/bash
jupyter contrib nbextension install --user
jupyter nbextension enable codefolding/main
jupyter nbextension enable autoscroll/main
jupyter trust ./dbsnp/MutationsInPdb.ipynb ./dbsnp/dbSNPTo3DChain.ipynb
jupyter labextension install jupyterlab_3dmol @jupyter-widgets/jupyterlab-manager
#jupyter labextension install jupyterlab_3dmol 
#jupyter labextension install @jupyter-widgets/jupyterlab-manager 
#jupyter lab build
